// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Forgot Password', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Forgot Password', async function() {
    await driver.get("http://35.225.238.45:3000/")
    await driver.manage().window().setRect(858, 824)
    await driver.findElement(By.id("slide-right-button")).click()
    await driver.findElement(By.css(".forgot-password")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("arjundevpk2001@gmail.com")
    await driver.findElement(By.id("login-btn")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("arjundevpk2001@gmail.com")
    await driver.findElement(By.id("login-btn")).click()
    await driver.close()
  })
})
