// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(858, 824)
    await driver.findElement(By.id("slide-right-button")).click()
    await driver.findElement(By.name("roll_no")).click()
    await driver.findElement(By.name("roll_no")).sendKeys("F18121")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("12345")
    await driver.findElement(By.css(".in")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("1234")
    await driver.findElement(By.css(".in")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).click()
    {
      const element = await driver.findElement(By.name("password"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.name("password")).sendKeys("admin")
    await driver.findElement(By.css(".in")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.close()
  })
})
