// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Log out', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Log out', async function() {
    await driver.get("http://35.225.238.45:3000/")
    await driver.manage().window().setRect(1051, 806)
    await driver.findElement(By.id("slide-right-button")).click()
    await driver.findElement(By.id("sign-in-form")).click()
    await driver.findElement(By.name("roll_no")).click()
    await driver.findElement(By.name("roll_no")).sendKeys("F18121")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("adim")
    await driver.findElement(By.css(".in")).click()
    {
      const element = await driver.findElement(By.css(".in"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("admin")
    await driver.findElement(By.css(".in")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.id("basic-nav-dropdown")).click()
    await driver.findElement(By.linkText("Logout")).click()
    await driver.close()
  })
})
