// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Register', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register', async function() {
    await driver.get("http://35.225.238.45:3000/")
    await driver.manage().window().setRect(858, 824)
    await driver.findElement(By.css("#sign-up-form > input:nth-child(1)")).click()
    await driver.findElement(By.css("#sign-up-form > input:nth-child(1)")).sendKeys("18204")
    await driver.findElement(By.name("dob")).click()
    await driver.findElement(By.name("dob")).sendKeys("2000-06-13")
    await driver.findElement(By.name("phone_no")).click()
    await driver.findElement(By.name("phone_no")).sendKeys("7089451235")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("aakash19@gmail.com")
    await driver.findElement(By.css("input:nth-child(5)")).click()
    await driver.findElement(By.css("input:nth-child(5)")).sendKeys("aak123")
    await driver.findElement(By.css(".up")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    {
      const element = await driver.findElement(By.css(".swal2-confirm"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.close()
  })
})
