// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Registration-validation', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Registration-validation', async function() {
    await driver.get("http://35.225.238.45:3000/")
    await driver.manage().window().setRect(1051, 806)
    await driver.findElement(By.css("#sign-up-form > input:nth-child(1)")).click()
    await driver.findElement(By.css("#sign-up-form > input:nth-child(1)")).sendKeys("18233")
    await driver.findElement(By.name("dob")).click()
    await driver.findElement(By.name("dob")).click()
    await driver.findElement(By.name("dob")).sendKeys("1999-11-12")
    await driver.findElement(By.name("phone_no")).click()
    await driver.findElement(By.css(".up")).click()
    await driver.close()
  })
})
