// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Update Profile', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Update Profile', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect(860, 824)
    await driver.findElement(By.id("slide-right-button")).click()
    await driver.findElement(By.name("roll_no")).click()
    await driver.findElement(By.name("roll_no")).sendKeys("18121")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("student")
    await driver.findElement(By.css(".in")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.findElement(By.css("strong")).click()
    await driver.findElement(By.id("basic-nav-dropdown")).click()
    await driver.findElement(By.linkText("Profile")).click()
    await driver.findElement(By.id("formCategory1")).click()
    await driver.findElement(By.id("formCategory1")).sendKeys("18121")
    await driver.findElement(By.id("formCategory2")).click()
    await driver.findElement(By.id("formCategory2")).sendKeys("asd@gmail.com")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    await driver.close()
  })
})
