// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('VIew Latest Updates', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('VIew Latest Updates', async function() {
    await driver.get("http://35.225.238.45:3000/")
    await driver.manage().window().setRect(858, 824)
    await driver.findElement(By.id("slide-right-button")).click()
    await driver.findElement(By.id("sign-in-form")).click()
    await driver.findElement(By.name("roll_no")).click()
    await driver.findElement(By.name("roll_no")).sendKeys("18121")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("student")
    await driver.findElement(By.css(".in")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
    {
      const element = await driver.findElement(By.css(".MuiIconButton-sizeSmall .MuiSvgIcon-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiIconButton-sizeSmall .MuiSvgIcon-root")).click()
    await driver.findElement(By.css(".MuiTableBody-root > .MuiTableRow-root > .MuiTableCell-sizeSmall:nth-child(2)")).click()
    await driver.close()
  })
})
